version: '3.8'

services:
  absensi-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: absensi-madrasah
    restart: always
    ports:
      - "85:3000"
    volumes:
      - ./backend/data:/app/data